version: '3'
services:
  backend:
    build: .
    ports:
      - '9292:9292'
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votetracker_backend_development
    depends_on:
      - db
    networks:
      - my_network
      - private
    expose:
      - 9292
  frontend:
    build: ../votetracker
    ports:
      - '3000:3000'
    # volumes:
    #   - ../votetracker:/app
    environment:
      NODE_ENV: production
    # extra_hosts:
    #   - "localhost:127.0.0.1"
    depends_on:
      - backend
    networks:
      - my_network
  db:
    image: postgres:latest
    volumes:
      - votetracker-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votetracker_backend_development
    networks: 
      - private
volumes: 
  votetracker-postgresql: 
networks:
  my_network:
  private:
