version: '2'
services:
  backend:
    build: .
    ports:
      - '9292:9292'
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votetracker_backend_development
    depends_on:
      - db
  # frontend:
  #   build: ./client
  #   ports:
  #     - '3001:3000'
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     NODE_ENV: development
  #   depends_on:
  #     - backend
  db:
    image: postgres:latest
    volumes:
      - /usr/local/share/postgresql@14:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votetracker_backend_development
